import Head from "next/head";
import { createClient } from "contentful";
import Image from "next/image";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import Link from "next/link";
export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "blogPost" });

  return {
    props: {
      posts: res.items,
    },
    revalidate: 1,
  };
}

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Contentful Example</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {posts.map((item, index) => {
          console.log(item.fields.heroImage);
          return (
            <div key={index}>
              <Link passHref href={`/posts/${item.fields.slug}`}>
                <div
                  style={{
                    padding: "30px",
                    background: "lightgrey",
                    border: "black solid thin",
                  }}
                >
                  <h1>{item.fields.title}</h1>
                  <Image
                    src={"https:" + item.fields.heroImage.fields.file.url}
                    height={200}
                    width={300}
                    alt="Hero image"
                  />
                </div>
              </Link>
            </div>
          );
        })}
      </div>
      <div></div>
    </div>
  );
}
